---
- name: Add apt key for node
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: true

- name: Add node 8 to sources
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_8.x xenial main"
    - "deb-src https://deb.nodesource.com/node_8.x xenial main"
  become: true

- name: Install nodejs
  apt:
    name: nodejs
    state: latest
    update_cache: true
  become: true

- name: Configure the Yarn APT key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
  become: true

- name: Add Yarn repository
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present
  become: true

- name: Install Yarn
  apt:
    name: yarn
    state: latest
    update_cache: true
  become: true