---
- name: Install ruby dev packages
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - build-essential
    - libmysqlclient-dev
  become: true

- name: Install bundler
  gem:
    name: bundler
    version: 1.16.1
  become: true
