---
- name: Add group
  group:
    name: "{{ deploy_user }}"
  become: true

- name: Add users
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups:
      - "{{ deploy_user }}"
      - sudo
  with_items: "{{ ssh_users }}"
  become: true

- name: Add ssh keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  become: true
  with_items: "{{ ssh_users }}"

- name: Allow passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  become: true

# https://askubuntu.com/questions/614534/disable-authentication-prompts-in-15-04/614537#614537
# Prevent asking to authenticate for users in the sudo group when using
# commands like systemctl
- name: Allow passwordless sudo for polkit
  template:
    src: nopassword.pkla.j2
    dest: /etc/polkit-1/localauthority/50-local.d/99-nopassword.pkla
  become: true

- name: Remove default ubuntu user
  user:
    name: ubuntu
    state: absent
    remove: true
  become: true
